### ISSUE TITLE
Slicer not copying files from one folder to the next.

### ISSUE THREAD

**Issue by mathless5** [Mojang/slicer#18]
Hello!
recently I tried making a texture pack for 1.20.4
My java version is 17, and i followed this video: https://www.youtube.com/watch?v=pSctvASenqI
I instead used slicer v1.1.3 instead of the youtuber, v1.1.2

when I paste the code into command prompt, it all prints out a lot of information, just like it should.
But, when I open up the blank folder it moved everything into, nothing is there.

Here is my file: (yes I extracted it before I followed the video, github just wont let me send the extracted file)
[MathsEnhancedPack.zip](https://github.com/Mojang/slicer/files/15051229/MathsEnhancedPack.zip)

I would love an explanation on how to fix this.

**Comment by satanicantichrist** [comment]
Hi, 
Resource packs can be still a .zip while using slicer.
I looked on your pack, and it looks like its already updated, so the slicer skips every file.

**Comment by mathless5** [comment]
> Hi, Resource packs can be still a .zip while using slicer. I looked on your pack, and it looks like its already updated, so the slicer skips every file.

Then why does everything in my texture pack work, except for the GUI?...
its simply invisible

**Comment by satanicantichrist** [comment]
> > Hi, Resource packs can be still a .zip while using slicer. I looked on your pack, and it looks like its already updated, so the slicer skips every file.
> 
> Then why does everything in my texture pack work, except for the GUI?... its simply invisible

Well I looked at the Resource pack you uploaded here, and it doesnt contain any container textures. This is the output pack or the pack you wanna slice?

**Comment by mathless5** [comment]
> > > Hi, Resource packs can be still a .zip while using slicer. I looked on your pack, and it looks like its already updated, so the slicer skips every file.
> > 
> > 
> > Then why does everything in my texture pack work, except for the GUI?... its simply invisible
> 
> Well I looked at the Resource pack you uploaded here, and it doesnt contain any container textures. This is the output pack or the pack you wanna slice?

the texture pack i sent is the one im trying to use, like thats the one im talking about
and I wont need slice like u said, i guess
and wdym theres no container? is that required? people told me to remove all unneccesary files

**Comment by mathless5** [comment]
the GUI I changed is under textures>gui>sprites>and the 3 folders in there
(changes mostly hotbar)

**Comment by satanicantichrist** [comment]
I just tested the pack and it works correctly.

**Comment by mathless5** [comment]
> I just tested the pack and it works correctly.

what verison are you playing on?

**Comment by satanicantichrist** [comment]
Tested it on 1.20.4.
If you have mods installed, they can break some stuff, or other resource pack. 
The pack it self is working. Try to look in logs, disable mods and other resource packs

**Comment by mathless5** [comment]
> Tested it on 1.20.4. If you have mods installed, they can break some stuff, or other resource pack. The pack it self is working. Try to look in logs, disable mods and other resource packs

for my friend and I, it does not work at all.
im using optifine, hes using Sodium and Essential
these should be fine, but it doesnt. Im honestly stumpted

like, I can see the critical hit that I changed but the GUI wont work.

**Comment by mathless5** [comment]
nevermind, I got it to work. Thanks
