### ISSUE TITLE
You are frustrating idiots

### ISSUE THREAD

**Issue by Dracconis** [Mojang/slicer#19]
You create a program that wont launch by itself AS a program and yet expect everyone else to know full well how they are suppose to use this utility WITHOUT ANY DAMN INSTRUCTIONS ON HOW TO USE IT. What you may think is self explanatory, like doing 2+2=4, is not the same for everyone else that has no idea how to make this work. 
These ARE NOT USAGE INSTRUCTIONS ON HOW TO USE THE SLICER TOOL:
"Usage
Pre-built jars are available through the [Releases](https://github.com/Mojang/slicer/releases) page. An installation of Java 17 or higher is required.

<"input dir or zip"> <"output dir"> [<"leftover dir">]

input dir or zip is the root of your resource pack (directory or zip containing an assets directory)
output dir will be filled with all processed texture files
leftover dir is optional location that will be filled with copies of source images with added highlights for areas that were migrated
The highlighted areas were processed by the tool and are used by the Vanilla game, the rest is not required in the pack"

Usage instructions would include what a person needs to do first in order to get the slicer tool working AND THEN what they would need to do next in order to get their Resource Pack sliced up by the tool.

**Comment by blryface** [comment]
Skill issue tbh

**Comment by blryface** [comment]
this is one of the issues of all time
