### ISSUE TITLE
some resource packs are converted weirdly

### ISSUE THREAD

**Issue by Lolothepro** [Mojang/slicer#6]
ie:
https://modrinth.com/resourcepack/custom-tabs/version/1.2

When I use slicer, it converts it to this
![2023-11-11_21 45 46](https://github.com/Mojang/slicer/assets/68275908/29fcf46d-af06-4d6b-a3ff-603c58fc7249)

I don't know if this is normal, so I prefer to report it.

**Comment by blank3times** [comment]
Oh, you're using a pack that has the items on the texture and hides the real ones with a core shader, you may have to update the core shader now or it might have broken. Look for the 'shaders' folder in the old resource pack and see if it's in the ne wone.
