### ISSUE TITLE
GUI images are cut off, making them stretched in game

### ISSUE THREAD

**Issue by SankFrinatra** [Mojang/slicer#7]
I'm trying to update a texture pack I use ([Clarity from SCtester](https://www.curseforge.com/minecraft/texture-packs/clarity) from 1.20.1 to 1.20.4. I am having issues where Slicer cuts off the right part of the villager GUI image (see first image), causing it to become stretched in game (see second image). The individual sprites that Slicer is supposed to create are also completely blank images (see third image for an example). I know Slicer is otherwise working correctly as other parts of the GUI have been converted and appear correctly.

Some extra info that might be pertinent:
1. The original villager GUI file was named villager.png and had to be renamed to villager2.png for Slicer to detect it and slice it.
2. The original villager GUI is 512x512 pixels.

![villager](https://github.com/Mojang/slicer/assets/153469371/109842fa-cfe9-4380-8a9b-7c8d72514d0c)

![in-game](https://github.com/Mojang/slicer/assets/153469371/58c9a799-e732-4206-a2e3-8657603f86ea)

![experience_bar_background](https://github.com/Mojang/slicer/assets/153469371/3e11c63c-c12b-467b-8baa-58eb8b714c29)

**Comment by VidTDM** [comment]
Is this only happening to `villager.png`?

**Comment by SankFrinatra** [comment]
Indeed, only on villager.png. Everything else slices fine and well. It might help to see that this is what the original villager2.png was (I was informed by the pack author that they used an outdated format - not sure if there's something to do about this with slicer other than change it to the current format manually)

![villager](https://github.com/Mojang/slicer/assets/153469371/ef5a1485-4e1d-4d01-9c71-23ccfacf32e7)

**Comment by lowercasebtw** [comment]
It's because villager.png was a leftover remanent from pre 1.14 days, the old villager GUI & as far as I know, its new counterpart villager2.png uses a different layout so this shouldn't be changed nor fix or anything as this pack needs a newer updated image & cant use a legacy old one

**Comment by lowercasebtw** [comment]
Unless they specifically check for villager2.png not existsing and villager.png existsing & use some other set of slice data but that won't happen as this is a older texture & many packs nowadays (besides packs before 1.14) dont have that texture

**Comment by VidTDM** [comment]
When I used it I didn't have any problems

**Comment by lowercasebtw** [comment]
@VidTDM Probably because your pack was made for 1.14+, or didn't have a villager.png texture

**Comment by SankFrinatra** [comment]
Indeed, I talked with the creator of the pack and they confirmed that the
pack was using the old villager GUI. Thanks for the help, everyone!

**Comment by lowercasebtw** [comment]
np
